### ISSUE TITLE
New users are not handled properly

### ISSUE THREAD

**Issue by micolous** [micolous/python-slackrealtime#2]
When a new user is created on a Slack instance, their SessionMetadata.users entry doesn't appear to be created.

This results in an exception being thrown when their presence is updated, eg:

```
          File "/usr/local/lib/python2.7/dist-packages/slackrealtime/session.py", line 174, in _update_deferred  
            self.users[event.user][u'presence'] = event.presence  
        exceptions.KeyError: u'UXXXXXXXX'
```

**Comment by brighid** [comment]
Point of information: we've built a Slack bot off of this library and run into this pretty regularly.

Thanks for writing this library, BTW. :)

**Comment by micolous** [comment]
@brighid Should be fixed now. That bug didn't cause me too many problems in my bots, as I never actually accessed the metadata associated with a user.

It's just a noisy error to have. :smile:

**Comment by habnabit** [comment]
As the primary maintainer of the aforementioned bot, I've just put this in use and I'll let you know if it fixes our issues. Thanks for the quick turnaround!
